name: LobbySwitcher
version: 1.1.0
author: cyne
main: gg.ninjagaming.lobbyswitcher.LobbySwitcher
api-version: 1.21

commands:
  lobbyswitcher:
    description: 'Main command of LobbySwitcher'
    aliases: lbsw